// Auto-generated by auto_probe_pcb.py -- Altium DelphiScript.
// In Altium Designer: File > Run Script..., then run GenerateProbeCard.
// Builds the probe-card PCB.

Var
    Board : IPCB_Board;

Procedure RegisterObj(Obj);
Begin
    Board.AddPCBObject(Obj);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast,
        PCBM_BoardRegisteration, Obj.I_ObjectAddress);
End;

Procedure AddLand(XMM, YMM : Double; Desig : String);
Var Pad;
Begin
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    Pad.X := MMsToCoord(XMM);
    Pad.Y := MMsToCoord(YMM);
    Pad.Layer := eMultiLayer;
    Pad.TopShape := eRounded;
    Pad.MidShape := eRounded;
    Pad.BotShape := eRounded;
    Pad.TopXSize := MMsToCoord(1.0000); Pad.TopYSize := MMsToCoord(1.0000);
    Pad.MidXSize := MMsToCoord(1.0000); Pad.MidYSize := MMsToCoord(1.0000);
    Pad.BotXSize := MMsToCoord(1.0000); Pad.BotYSize := MMsToCoord(1.0000);
    Pad.HoleSize := MMsToCoord(0.5080);
    Pad.Plated := True;
    Pad.Name := Desig;
    RegisterObj(Pad);
End;

Procedure AddText(XMM, YMM, Rot : Double; S : String);
Var T;
Begin
    T := PCBServer.PCBObjectFactory(eTextObject, eNoDimension, eCreate_Default);
    T.XLocation := MMsToCoord(XMM);
    T.YLocation := MMsToCoord(YMM);
    T.Layer := eTopOverlay;
    T.Size := MMsToCoord(0.4000);
    T.Width := MMsToCoord(0.0600);
    T.Rotation := Rot;
    T.Text := S;
    RegisterObj(T);
End;

Procedure AddRefTrack(X1, Y1, X2, Y2, Wid : Double);
Var Tr;
Begin
    Tr := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    Tr.X1 := MMsToCoord(X1); Tr.Y1 := MMsToCoord(Y1);
    Tr.X2 := MMsToCoord(X2); Tr.Y2 := MMsToCoord(Y2);
    Tr.Width := MMsToCoord(Wid);
    Tr.Layer := eMechanical13;
    RegisterObj(Tr);
End;

Procedure AddProbe(X1, Y1, X2, Y2 : Double);
Begin
    AddRefTrack(X1, Y1, X2, Y2, 0.1500);
End;

// --- everything belonging to one probe: the solder land, its silk label,
// --- and the probe needle running from the land to the die-pad coordinate.
Procedure EmitLand(LX, LY : Double; Desig : String;
                   TX, TY, Rot : Double; Sig : String; DX, DY : Double);
Begin
    AddLand(LX, LY, Desig);
    AddText(TX, TY, Rot, Sig);
    AddProbe(LX, LY, DX, DY);
End;

// --- board shape: rectangular outline.
// --- Segments[i] returns the record BY VALUE, so "Segments[i].vx := ..."
// --- edits a throwaway copy and does nothing. Build a local TPolySegment
// --- and assign it back into Segments[i].
Procedure SetOutlinePoint(Idx : Integer; XMM, YMM : Double);
Var Seg : TPolySegment;
Begin
    Seg := Board.BoardOutline.Segments[Idx];
    Seg.Kind := ePolySegmentLine;
    Seg.vx := MMsToCoord(XMM);
    Seg.vy := MMsToCoord(YMM);
    Board.BoardOutline.Segments[Idx] := Seg;
End;

Procedure SetRectBoard(X1, Y1, X2, Y2 : Double);
Begin
    Board.BoardOutline.Invalidate;
    Board.BoardOutline.PointCount := 4;
    SetOutlinePoint(0, X1, Y1);
    SetOutlinePoint(1, X2, Y1);
    SetOutlinePoint(2, X2, Y2);
    SetOutlinePoint(3, X1, Y2);
    Board.BoardOutline.Validate;
    Board.ViewManager_FullUpdate;
End;

// --- circular aperture: board-cutout region approximated by a 72-gon.
// --- The region-contour API is the part most likely to need adjustment
// --- for your Altium version.
Procedure AddCircleCutout(CXmm, CYmm, Rmm : Double);
Var Rgn, C, i, ang;
Begin
    Rgn := PCBServer.PCBObjectFactory(eRegionObject, eNoDimension, eCreate_Default);
    Rgn.SetState_Kind(eRegionKind_BoardCutout);
    C := PCBServer.PCBContourFactory;
    For i := 0 To 71 Do
    Begin
        ang := i * 6.28318530717959 / 72.0;
        C.AddPoint(MMsToCoord(CXmm + Rmm * Cos(ang)), MMsToCoord(CYmm + Rmm * Sin(ang)));
    End;
    Rgn.SetOutlineContour(C);
    Rgn.Layer := eTopLayer;
    RegisterObj(Rgn);
End;

// --- die-aspect clearance marker on a non-fabricated mechanical layer.
Procedure AddMarkerTrack(X1, Y1, X2, Y2, Wid : Double);
Var Tr;
Begin
    Tr := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    Tr.X1 := MMsToCoord(X1); Tr.Y1 := MMsToCoord(Y1);
    Tr.X2 := MMsToCoord(X2); Tr.Y2 := MMsToCoord(Y2);
    Tr.Width := MMsToCoord(Wid);
    Tr.Layer := eMechanical15;
    RegisterObj(Tr);
End;

Procedure AddMarkerRect(X1, Y1, X2, Y2, Wid : Double);
Begin
    AddMarkerTrack(X1, Y1, X2, Y1, Wid);
    AddMarkerTrack(X2, Y1, X2, Y2, Wid);
    AddMarkerTrack(X2, Y2, X1, Y2, Wid);
    AddMarkerTrack(X1, Y2, X1, Y1, Wid);
End;

// --- turn off mechanical layers this script never draws on (only M13 and
// --- M15 are used). Wrapped in Try/Except because the layer-enable API
// --- differs across Altium versions; UNVERIFIED. The copper, paste, solder,
// --- overlay, keep-out, drill and multi-layer layers are intrinsic and
// --- cannot be deleted -- at most hidden -- so they are left alone.
Procedure DisableUnusedMechLayers;
Begin
    Try
        Board.LayerStack_V7.LayerObject_V7[eMechanical1].MechanicalLayerEnabled := False;
    Except
        Try
            Board.MechanicalLayerEnabled[eMechanical1] := False;
        Except
        End;
    End;
End;

Procedure BuildAll;
Begin
    EmitLand(87.2090, 96.7500, 'T1', 87.0090, 98.9580, 90.0000, 'VSS', 98.5250, 78.2250);
    EmitLand(87.9110, 97.9500, 'T2', 87.7110, 98.9580, 90.0000, 'VSS', 98.6750, 78.2250);
    EmitLand(88.6130, 96.7500, 'T3', 88.4130, 98.9580, 90.0000, 'VSS', 98.8250, 78.2250);
    EmitLand(89.3150, 97.9500, 'T4', 89.1150, 98.9580, 90.0000, 'IN_1_7', 98.9750, 78.2250);
    EmitLand(90.0170, 96.7500, 'T5', 89.8170, 98.9580, 90.0000, 'VSS', 99.1250, 78.2250);
    EmitLand(90.7190, 97.9500, 'T6', 90.5190, 98.9580, 90.0000, 'VSS', 99.2750, 78.2250);
    EmitLand(91.4210, 96.7500, 'T7', 91.2210, 98.9580, 90.0000, 'VSS', 99.4250, 78.2250);
    EmitLand(92.1230, 97.9500, 'T8', 91.9230, 98.9580, 90.0000, 'IN_1_15', 99.5750, 78.2250);
    EmitLand(92.8250, 96.7500, 'T9', 92.6250, 98.9580, 90.0000, 'VSS', 99.7250, 78.2250);
    EmitLand(93.5270, 97.9500, 'T10', 93.3270, 98.9580, 90.0000, 'VSS', 99.8750, 78.2250);
    EmitLand(94.2290, 96.7500, 'T11', 94.0290, 98.9580, 90.0000, 'VSS', 100.0250, 78.2250);
    EmitLand(94.9310, 97.9500, 'T12', 94.7310, 98.9580, 90.0000, 'IN_1_23', 100.1750, 78.2250);
    EmitLand(95.6330, 96.7500, 'T13', 95.4330, 98.9580, 90.0000, 'VSS', 100.3250, 78.2250);
    EmitLand(96.3350, 97.9500, 'T14', 96.1350, 98.9580, 90.0000, 'VSS', 100.4750, 78.2250);
    EmitLand(97.0370, 96.7500, 'T15', 96.8370, 98.9580, 90.0000, 'VSS', 100.6250, 78.2250);
    EmitLand(97.7390, 97.9500, 'T16', 97.5390, 98.9580, 90.0000, 'IN_1_31', 100.7750, 78.2250);
    EmitLand(98.4410, 96.7500, 'T17', 98.2410, 98.9580, 90.0000, 'VSS', 100.9250, 78.2250);
    EmitLand(99.1430, 97.9500, 'T18', 98.9430, 98.9580, 90.0000, 'VSS', 101.0750, 78.2250);
    EmitLand(99.8450, 96.7500, 'T19', 99.6450, 98.9580, 90.0000, 'VSS', 101.2250, 78.2250);
    EmitLand(100.5470, 97.9500, 'T20', 100.3470, 98.9580, 90.0000, 'IN_1_39', 101.3750, 78.2250);
    EmitLand(101.2490, 96.7500, 'T21', 101.0490, 98.9580, 90.0000, 'VSS', 101.5250, 78.2250);
    EmitLand(101.9510, 97.9500, 'T22', 101.7510, 98.9580, 90.0000, 'VSS', 101.6750, 78.2250);
    EmitLand(102.6530, 96.7500, 'T23', 102.4530, 98.9580, 90.0000, 'VSS', 101.8250, 78.2250);
    EmitLand(103.3550, 97.9500, 'T24', 103.1550, 98.9580, 90.0000, 'IN_1_47', 101.9750, 78.2250);
    EmitLand(104.0570, 96.7500, 'T25', 103.8570, 98.9580, 90.0000, 'VSS', 102.1250, 78.2250);
    EmitLand(104.7590, 97.9500, 'T26', 104.5590, 98.9580, 90.0000, 'VSS', 102.2750, 78.2250);
    EmitLand(105.4610, 96.7500, 'T27', 105.2610, 98.9580, 90.0000, 'VSS', 102.4250, 78.2250);
    EmitLand(106.1630, 97.9500, 'T28', 105.9630, 98.9580, 90.0000, 'IN_1_55', 102.5750, 78.2250);
    EmitLand(106.8650, 96.7500, 'T29', 106.6650, 98.9580, 90.0000, 'VSS', 102.7250, 78.2250);
    EmitLand(107.5670, 97.9500, 'T30', 107.3670, 98.9580, 90.0000, 'VSS', 102.8750, 78.2250);
    EmitLand(108.2690, 96.7500, 'T31', 108.0690, 98.9580, 90.0000, 'VSS', 103.0250, 78.2250);
    EmitLand(108.9710, 97.9500, 'T32', 108.7710, 98.9580, 90.0000, 'IN_1_63', 103.1750, 78.2250);
    EmitLand(109.6730, 96.7500, 'T33', 109.4730, 98.9580, 90.0000, 'VSS', 103.3250, 78.2250);
    EmitLand(110.3750, 97.9500, 'T34', 110.1750, 98.9580, 90.0000, 'VSS', 103.4750, 78.2250);
    EmitLand(111.0770, 96.7500, 'T35', 110.8770, 98.9580, 90.0000, 'VSS', 103.6250, 78.2250);
    EmitLand(111.7790, 97.9500, 'T36', 111.5790, 98.9580, 90.0000, 'IN_1_71', 103.7750, 78.2250);
    EmitLand(112.4810, 96.7500, 'T37', 112.2810, 98.9580, 90.0000, 'VSS', 103.9250, 78.2250);
    EmitLand(113.1830, 97.9500, 'T38', 112.9830, 98.9580, 90.0000, 'VSS', 104.0750, 78.2250);
    EmitLand(113.8850, 96.7500, 'T39', 113.6850, 98.9580, 90.0000, 'VSS', 104.2250, 78.2250);
    EmitLand(114.5870, 97.9500, 'T40', 114.3870, 98.9580, 90.0000, 'OUT_2', 104.3750, 78.2250);
    EmitLand(115.2890, 96.7500, 'T41', 115.0890, 98.9580, 90.0000, 'VSS', 104.5250, 78.2250);
    EmitLand(115.9910, 97.9500, 'T42', 115.7910, 98.9580, 90.0000, 'VSS', 104.6750, 78.2250);
    EmitLand(87.2090, 55.6500, 'B1', 87.0090, 52.1220, 90.0000, 'VDD', 98.5250, 74.1750);
    EmitLand(87.9110, 54.4500, 'B2', 87.7110, 52.1220, 90.0000, 'VDD', 98.6750, 74.1750);
    EmitLand(88.6130, 55.6500, 'B3', 88.4130, 52.1220, 90.0000, 'VDD', 98.8250, 74.1750);
    EmitLand(89.3150, 54.4500, 'B4', 89.1150, 52.1220, 90.0000, 'VDD', 98.9750, 74.1750);
    EmitLand(90.0170, 55.6500, 'B5', 89.8170, 52.1220, 90.0000, 'VDD', 99.1250, 74.1750);
    EmitLand(90.7190, 54.4500, 'B6', 90.5190, 52.1220, 90.0000, 'VDD', 99.2750, 74.1750);
    EmitLand(91.4210, 55.6500, 'B7', 91.2210, 52.1220, 90.0000, 'VDD', 99.4250, 74.1750);
    EmitLand(92.1230, 54.4500, 'B8', 91.9230, 52.1220, 90.0000, 'VDD', 99.5750, 74.1750);
    EmitLand(92.8250, 55.6500, 'B9', 92.6250, 52.1220, 90.0000, 'VDD', 99.7250, 74.1750);
    EmitLand(93.5270, 54.4500, 'B10', 93.3270, 52.1220, 90.0000, 'VDD', 99.8750, 74.1750);
    EmitLand(94.2290, 55.6500, 'B11', 94.0290, 52.1220, 90.0000, 'VDD', 100.0250, 74.1750);
    EmitLand(94.9310, 54.4500, 'B12', 94.7310, 52.1220, 90.0000, 'VDD', 100.1750, 74.1750);
    EmitLand(95.6330, 55.6500, 'B13', 95.4330, 52.1220, 90.0000, 'VDD', 100.3250, 74.1750);
    EmitLand(96.3350, 54.4500, 'B14', 96.1350, 52.1220, 90.0000, 'VDD', 100.4750, 74.1750);
    EmitLand(97.0370, 55.6500, 'B15', 96.8370, 52.1220, 90.0000, 'VDD', 100.6250, 74.1750);
    EmitLand(97.7390, 54.4500, 'B16', 97.5390, 52.1220, 90.0000, 'VDD', 100.7750, 74.1750);
    EmitLand(98.4410, 55.6500, 'B17', 98.2410, 52.1220, 90.0000, 'VDD', 100.9250, 74.1750);
    EmitLand(99.1430, 54.4500, 'B18', 98.9430, 52.1220, 90.0000, 'VDD', 101.0750, 74.1750);
    EmitLand(99.8450, 55.6500, 'B19', 99.6450, 52.1220, 90.0000, 'VDD', 101.2250, 74.1750);
    EmitLand(100.5470, 54.4500, 'B20', 100.3470, 52.1220, 90.0000, 'VDD', 101.3750, 74.1750);
    EmitLand(101.2490, 55.6500, 'B21', 101.0490, 52.1220, 90.0000, 'VDD', 101.5250, 74.1750);
    EmitLand(101.9510, 54.4500, 'B22', 101.7510, 52.1220, 90.0000, 'VDD', 101.6750, 74.1750);
    EmitLand(102.6530, 55.6500, 'B23', 102.4530, 52.1220, 90.0000, 'VDD', 101.8250, 74.1750);
    EmitLand(103.3550, 54.4500, 'B24', 103.1550, 52.1220, 90.0000, 'VDD', 101.9750, 74.1750);
    EmitLand(104.0570, 55.6500, 'B25', 103.8570, 52.1220, 90.0000, 'VDD', 102.1250, 74.1750);
    EmitLand(104.7590, 54.4500, 'B26', 104.5590, 52.1220, 90.0000, 'VDD', 102.2750, 74.1750);
    EmitLand(105.4610, 55.6500, 'B27', 105.2610, 52.1220, 90.0000, 'VDD', 102.4250, 74.1750);
    EmitLand(106.1630, 54.4500, 'B28', 105.9630, 52.1220, 90.0000, 'VDD', 102.5750, 74.1750);
    EmitLand(106.8650, 55.6500, 'B29', 106.6650, 52.1220, 90.0000, 'VDD', 102.7250, 74.1750);
    EmitLand(107.5670, 54.4500, 'B30', 107.3670, 52.1220, 90.0000, 'VDD', 102.8750, 74.1750);
    EmitLand(108.2690, 55.6500, 'B31', 108.0690, 52.1220, 90.0000, 'VDD', 103.0250, 74.1750);
    EmitLand(108.9710, 54.4500, 'B32', 108.7710, 52.1220, 90.0000, 'VDD', 103.1750, 74.1750);
    EmitLand(109.6730, 55.6500, 'B33', 109.4730, 52.1220, 90.0000, 'VDD', 103.3250, 74.1750);
    EmitLand(110.3750, 54.4500, 'B34', 110.1750, 52.1220, 90.0000, 'VDD', 103.4750, 74.1750);
    EmitLand(111.0770, 55.6500, 'B35', 110.8770, 52.1220, 90.0000, 'VDD', 103.6250, 74.1750);
    EmitLand(111.7790, 54.4500, 'B36', 111.5790, 52.1220, 90.0000, 'VDD', 103.7750, 74.1750);
    EmitLand(112.4810, 55.6500, 'B37', 112.2810, 52.1220, 90.0000, 'VDD', 103.9250, 74.1750);
    EmitLand(113.1830, 54.4500, 'B38', 112.9830, 52.1220, 90.0000, 'VDD', 104.0750, 74.1750);
    EmitLand(113.8850, 55.6500, 'B39', 113.6850, 50.3620, 90.0000, 'IN_2_78', 104.2250, 74.1750);
    EmitLand(114.5870, 54.4500, 'B40', 114.3870, 52.1220, 90.0000, 'VDD', 104.3750, 74.1750);
    EmitLand(115.2890, 55.6500, 'B41', 115.0890, 52.1220, 90.0000, 'VDD', 104.5250, 74.1750);
    EmitLand(115.9910, 54.4500, 'B42', 115.7910, 52.1220, 90.0000, 'VDD', 104.6750, 74.1750);
    EmitLand(77.6250, 67.4250, 'L1', 74.0970, 67.2250, 0.0000, 'VSS', 98.5250, 74.3250);
    EmitLand(76.4250, 68.1270, 'L2', 74.0970, 67.9270, 0.0000, 'VSS', 98.5250, 74.4750);
    EmitLand(77.6250, 68.8290, 'L3', 74.0970, 68.6290, 0.0000, 'VSS', 98.5250, 74.6250);
    EmitLand(76.4250, 69.5310, 'L4', 74.0970, 69.3310, 0.0000, 'VSS', 98.5250, 74.7750);
    EmitLand(77.6250, 70.2330, 'L5', 74.0970, 70.0330, 0.0000, 'VSS', 98.5250, 74.9250);
    EmitLand(76.4250, 70.9350, 'L6', 74.0970, 70.7350, 0.0000, 'VSS', 98.5250, 75.0750);
    EmitLand(77.6250, 71.6370, 'L7', 74.0970, 71.4370, 0.0000, 'VSS', 98.5250, 75.2250);
    EmitLand(76.4250, 72.3390, 'L8', 74.0970, 72.1390, 0.0000, 'VSS', 98.5250, 75.3750);
    EmitLand(77.6250, 73.0410, 'L9', 74.0970, 72.8410, 0.0000, 'VSS', 98.5250, 75.5250);
    EmitLand(76.4250, 73.7430, 'L10', 74.0970, 73.5430, 0.0000, 'VSS', 98.5250, 75.6750);
    EmitLand(77.6250, 74.4450, 'L11', 74.0970, 74.2450, 0.0000, 'VSS', 98.5250, 75.8250);
    EmitLand(76.4250, 75.1470, 'L12', 74.0970, 74.9470, 0.0000, 'VSS', 98.5250, 75.9750);
    EmitLand(77.6250, 75.8490, 'L13', 74.0970, 75.6490, 0.0000, 'VSS', 98.5250, 76.1250);
    EmitLand(76.4250, 76.5510, 'L14', 73.2170, 76.3510, 0.0000, 'OUT_1', 98.5250, 76.2750);
    EmitLand(77.6250, 77.2530, 'L15', 74.0970, 77.0530, 0.0000, 'VSS', 98.5250, 76.4250);
    EmitLand(76.4250, 77.9550, 'L16', 74.0970, 77.7550, 0.0000, 'VSS', 98.5250, 76.5750);
    EmitLand(77.6250, 78.6570, 'L17', 74.0970, 78.4570, 0.0000, 'VSS', 98.5250, 76.7250);
    EmitLand(76.4250, 79.3590, 'L18', 71.8970, 79.1590, 0.0000, 'IN_1_101', 98.5250, 76.8750);
    EmitLand(77.6250, 80.0610, 'L19', 74.0970, 79.8610, 0.0000, 'VSS', 98.5250, 77.0250);
    EmitLand(76.4250, 80.7630, 'L20', 74.0970, 80.5630, 0.0000, 'VSS', 98.5250, 77.1750);
    EmitLand(77.6250, 81.4650, 'L21', 74.0970, 81.2650, 0.0000, 'VSS', 98.5250, 77.3250);
    EmitLand(76.4250, 82.1670, 'L22', 72.3370, 81.9670, 0.0000, 'IN_1_93', 98.5250, 77.4750);
    EmitLand(77.6250, 82.8690, 'L23', 74.0970, 82.6690, 0.0000, 'VSS', 98.5250, 77.6250);
    EmitLand(76.4250, 83.5710, 'L24', 74.0970, 83.3710, 0.0000, 'VSS', 98.5250, 77.7750);
    EmitLand(77.6250, 84.2730, 'L25', 74.0970, 84.0730, 0.0000, 'VSS', 98.5250, 77.9250);
    EmitLand(76.4250, 84.9750, 'L26', 72.3370, 84.7750, 0.0000, 'IN_1_85', 98.5250, 78.0750);
    EmitLand(125.5750, 67.4250, 'R1', 127.7830, 67.2250, 0.0000, 'IN_2_136', 104.6750, 74.3250);
    EmitLand(126.7750, 68.1270, 'R2', 127.7830, 67.9270, 0.0000, 'VDD', 104.6750, 74.4750);
    EmitLand(125.5750, 68.8290, 'R3', 127.7830, 68.6290, 0.0000, 'VDD', 104.6750, 74.6250);
    EmitLand(126.7750, 69.5310, 'R4', 127.7830, 69.3310, 0.0000, 'VDD', 104.6750, 74.7750);
    EmitLand(125.5750, 70.2330, 'R5', 127.7830, 70.0330, 0.0000, 'IN_2_128', 104.6750, 74.9250);
    EmitLand(126.7750, 70.9350, 'R6', 127.7830, 70.7350, 0.0000, 'VDD', 104.6750, 75.0750);
    EmitLand(125.5750, 71.6370, 'R7', 127.7830, 71.4370, 0.0000, 'VDD', 104.6750, 75.2250);
    EmitLand(126.7750, 72.3390, 'R8', 127.7830, 72.1390, 0.0000, 'VDD', 104.6750, 75.3750);
    EmitLand(125.5750, 73.0410, 'R9', 127.7830, 72.8410, 0.0000, 'IN_2_120', 104.6750, 75.5250);
    EmitLand(126.7750, 73.7430, 'R10', 127.7830, 73.5430, 0.0000, 'VDD', 104.6750, 75.6750);
    EmitLand(125.5750, 74.4450, 'R11', 127.7830, 74.2450, 0.0000, 'VDD', 104.6750, 75.8250);
    EmitLand(126.7750, 75.1470, 'R12', 127.7830, 74.9470, 0.0000, 'VDD', 104.6750, 75.9750);
    EmitLand(125.5750, 75.8490, 'R13', 127.7830, 75.6490, 0.0000, 'IN_2_112', 104.6750, 76.1250);
    EmitLand(126.7750, 76.5510, 'R14', 127.7830, 76.3510, 0.0000, 'VDD', 104.6750, 76.2750);
    EmitLand(125.5750, 77.2530, 'R15', 127.7830, 77.0530, 0.0000, 'VDD', 104.6750, 76.4250);
    EmitLand(126.7750, 77.9550, 'R16', 127.7830, 77.7550, 0.0000, 'VDD', 104.6750, 76.5750);
    EmitLand(125.5750, 78.6570, 'R17', 127.7830, 78.4570, 0.0000, 'IN_2_104', 104.6750, 76.7250);
    EmitLand(126.7750, 79.3590, 'R18', 127.7830, 79.1590, 0.0000, 'VDD', 104.6750, 76.8750);
    EmitLand(125.5750, 80.0610, 'R19', 127.7830, 79.8610, 0.0000, 'VDD', 104.6750, 77.0250);
    EmitLand(126.7750, 80.7630, 'R20', 127.7830, 80.5630, 0.0000, 'VDD', 104.6750, 77.1750);
    EmitLand(125.5750, 81.4650, 'R21', 127.7830, 81.2650, 0.0000, 'IN_2_96', 104.6750, 77.3250);
    EmitLand(126.7750, 82.1670, 'R22', 127.7830, 81.9670, 0.0000, 'VDD', 104.6750, 77.4750);
    EmitLand(125.5750, 82.8690, 'R23', 127.7830, 82.6690, 0.0000, 'VDD', 104.6750, 77.6250);
    EmitLand(126.7750, 83.5710, 'R24', 127.7830, 83.3710, 0.0000, 'VDD', 104.6750, 77.7750);
    EmitLand(125.5750, 84.2730, 'R25', 127.7830, 84.0730, 0.0000, 'IN_2_88', 104.6750, 77.9250);
    EmitLand(126.7750, 84.9750, 'R26', 127.7830, 84.7750, 0.0000, 'VDD', 104.6750, 78.0750);
End;

Procedure GenerateProbeCard;
Begin
    If PCBServer = Nil Then
    Begin
        ShowMessage('PCBServer is nil -- the PCB editor is not loaded.');
        Exit;
    End;
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('No PCB is open. Create a blank PCB first: ' +
            'File > New > PCB, make that tab active, then run this script again.');
        Exit;
    End;
    PCBServer.PreProcess;
    DisableUnusedMechLayers;
    SetRectBoard(44.3500, -18.0500, 158.8500, 170.4500);
    AddCircleCutout(101.6000, 76.2000, 8.0057);
    AddMarkerRect(79.3750, 57.1500, 123.8250, 95.2500, 0.1500);
    BuildAll;
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    Client.SendMessage('PCB:Zoom', 'Action=Redraw', 255, Client.CurrentView);
    ShowMessage('Probe card built on the active PCB. ' +
        'Use File > Save As to save it as a .PcbDoc.');
End;

