// Auto-generated by auto_probe_pcb.py -- Altium Sch-library DelphiScript.
//
// ENTRY POINTS (File > Run Script... and pick one):
//
//   GenerateSymbol      Main. Builds the multi-part 'ProbeCard' component in
//                       the ACTIVE schematic library.
//
//   ListOpenDocuments   Diagnostic. Dumps every document Altium currently has
//                       loaded, with the exact registered path string. Use it
//                       to find the value for STALE_LIB_PATH.
//
//   CloseStaleLibrary   Evicts Altium's cached copy of a library at
//                       STALE_LIB_PATH. Run on its own, NOT from inside
//                       GenerateSymbol -- closing a document invalidates every
//                       ISch_ interface the generator holds.
//
// ---------------------------------------------------------------------------
// WORKFLOW WHEN DUPLICATES APPEAR ACROSS RUNS
//
//   1. Delete the .SchLib from disk.
//   2. Run ListOpenDocuments. If a SCHLIB entry still points at the file you
//      just deleted, that cached document is your duplicate source.
//   3. Copy that path into STALE_LIB_PATH, run CloseStaleLibrary.
//   4. Create the new library, make it active, run GenerateSymbol.
//
// GenerateSymbol also reports how many pre-existing copies it stripped. A
// non-zero count on a library you just created from scratch is proof Altium
// handed you a cached document.
// ---------------------------------------------------------------------------

Const
    COMP_NAME          = 'ProbeCard';
    FP_NAME            = 'ProbeCard';

    // OPTIONAL override. CloseStaleLibrary discovers stale libraries on its
    // own, so leave this blank unless the scan misses the one you want. If
    // set, it is always processed and bypasses the missing-file filter below.
    // Get the exact string from ShowCurrentLibPath -- do not type it from
    // Explorer.
    STALE_LIB_PATH     = '';

    // True  = only close libraries whose file is MISSING from disk. A library
    //         Altium still has registered but that no longer exists on disk is
    //         stale by definition -- this is the delete-then-regenerate case,
    //         and it leaves libraries you are actively using untouched.
    // False = close every schematic library the scan finds. Only do this if
    //         you know nothing else open matters.
    CLOSE_ONLY_MISSING_FILES = True;

    // If True, CloseStaleLibrary also deletes the file from disk after closing.
    DELETE_AFTER_CLOSE = False;

    // Last resort. If a document reports CanClose = False and will not release,
    // setting BeingClosed marks it as mid-destruction so CloseDocument will
    // proceed. This flag is normally set by Altium's own close machinery, not
    // by scripts -- if CloseDocument then still fails, you are left with a
    // document flagged as closing that never closed, and the only clean
    // recovery is restarting Altium. Leave False unless you are stuck.
    FORCE_BEING_CLOSED = False;

Var
    Lib  : ISch_Lib;
    Comp : ISch_Component;


Function BoolStr(V : Boolean) : String;
Begin
    If V Then Result := 'True' Else Result := 'False';
End;


// ---------------------------------------------------------------------------
// Diagnostic 1 (PREFERRED): print the active library's registered path.
//
// This is the string to paste into STALE_LIB_PATH. Run it while the library is
// open and focused, BEFORE you close and delete it. DocumentName is exactly
// how Altium registered the document, so it is guaranteed to match what
// GetDocumentByPath expects -- no transcription risk.
// ---------------------------------------------------------------------------
Procedure ShowCurrentLibPath;
Var
    D : ISch_Document;
Begin
    If SchServer = Nil Then
    Begin
        ShowMessage('SchServer is nil -- the schematic editor is not loaded.');
        Exit;
    End;

    D := SchServer.GetCurrentSchDocument;
    If D = Nil Then
    Begin
        ShowMessage('No schematic document is focused. Click into the .SchLib ' +
            'editor tab and run again.');
        Exit;
    End;

    ShowMessage('Registered path of the active document:' + #13#10#13#10 +
        D.DocumentName + #13#10#13#10 +
        'Copy this into STALE_LIB_PATH exactly as shown.');
End;


// ---------------------------------------------------------------------------
// Diagnostic 2: enumerate documents Altium has loaded, via the workspace.
//
// Standalone (non-project) documents live under a pseudo-project named
// 'Free Documents'. Note this lists documents the workspace knows about --
// a cached document that has been detached from the workspace may not appear
// here even though GetDocumentByPath still returns it. The definitive cache
// test is CloseStaleLibrary itself: if it reports 'No cached document', the
// cache is clean for that path.
// ---------------------------------------------------------------------------
Procedure ListOpenDocuments;
Var
    WS   : IWorkspace;
    Prj  : IProject;
    Doc  : IDocument;
    I, J : Integer;
    Rpt  : TStringList;
Begin
    WS := GetWorkspace;
    If WS = Nil Then
    Begin
        ShowMessage('No workspace available.');
        Exit;
    End;

    Rpt := TStringList.Create;
    Try
        Rpt.Add('Projects: ' + IntToStr(WS.DM_ProjectCount));
        Rpt.Add('');

        For I := 0 To WS.DM_ProjectCount - 1 Do
        Begin
            Prj := WS.DM_Projects(I);
            If Prj <> Nil Then
            Begin
                Rpt.Add('=== ' + Prj.DM_ProjectFileName + ' ===');

                For J := 0 To Prj.DM_LogicalDocumentCount - 1 Do
                Begin
                    Doc := Prj.DM_LogicalDocuments(J);
                    If Doc <> Nil Then
                        Rpt.Add('  [' + Doc.DM_DocumentKind + '] ' +
                                Doc.DM_FullPath);
                End;

                Rpt.Add('');
            End;
        End;

        Rpt.Add('---');
        Rpt.Add('Copy any SCHLIB path above into STALE_LIB_PATH byte-for-byte.');
        Rpt.Add('If the library is currently open, ShowCurrentLibPath is more');
        Rpt.Add('reliable -- it reads the path straight off the document.');
        ShowMessage(Rpt.Text);
    Finally
        Rpt.Free;
    End;
End;


// ---------------------------------------------------------------------------
// Close one cached document by path. Returns a human-readable status line.
// ---------------------------------------------------------------------------
Function CloseOneDocument(APath : String) : String;
Var
    ServerDoc  : IServerDocument;
    CanCloseIt : Boolean;
Begin
    ServerDoc := Client.GetDocumentByPath(APath);

    If ServerDoc = Nil Then
    Begin
        // Nil means no cached copy -- the good outcome, not an error.
        Result := 'not cached (already clean)';
        Exit;
    End;

    // If Altium is already tearing this document down, do not interfere.
    If ServerDoc.GetBeingClosed Then
    Begin
        Result := 'SKIPPED - already mid-close';
        Exit;
    End;

    ServerDoc.SetModified(False);   // suppress the save prompt

    CanCloseIt := ServerDoc.GetCanClose;
    If CanCloseIt = False Then
    Begin
        If FORCE_BEING_CLOSED Then
            // Flag as mid-destruction so CloseDocument will go through.
            // See the warning on the const before enabling this.
            ServerDoc.SetBeingClosed(True)
        Else
        Begin
            Result := 'BLOCKED - CanClose=False (open tab or project holds it)';
            Exit;
        End;
    End;

    Client.CloseDocument(ServerDoc);

    // Verify the eviction took, rather than assuming it did.
    If Client.GetDocumentByPath(APath) <> Nil Then
    Begin
        Result := 'FAILED - still cached after CloseDocument; restart Altium';
        Exit;
    End;

    If DELETE_AFTER_CLOSE Then
        If FileExists(APath) Then
            DeleteFile(APath);

    Result := 'CLOSED';
End;


// ---------------------------------------------------------------------------
// Stale-document eviction. Run on its own, before creating the new library.
//
// Self-discovering: walks the workspace for SCHLIB documents rather than
// making you transcribe a path. By default it only touches libraries whose
// file is MISSING from disk -- a library Altium still has registered but that
// no longer exists on disk is stale by definition, and that is precisely the
// delete-then-regenerate case. Libraries you are actively using are left
// alone because their files still exist.
//
// STALE_LIB_PATH, if set, is always processed in addition to whatever the
// scan finds, and bypasses the missing-file filter.
// ---------------------------------------------------------------------------
Procedure CloseStaleLibrary;
Var
    WS       : IWorkspace;
    Prj      : IProject;
    Doc      : IDocument;
    I, J     : Integer;
    Cands    : TStringList;
    Rpt      : TStringList;
    P        : String;
    Status   : String;
    Wanted   : Boolean;
    NumClosed: Integer;
Begin
    Cands := TStringList.Create;
    Rpt   := TStringList.Create;
    Try
        // Explicit override first -- bypasses the missing-file filter.
        If STALE_LIB_PATH <> '' Then
            Cands.Add(STALE_LIB_PATH);

        // Scan the workspace for schematic libraries.
        WS := GetWorkspace;
        If WS <> Nil Then
        Begin
            For I := 0 To WS.DM_ProjectCount - 1 Do
            Begin
                Prj := WS.DM_Projects(I);
                If Prj <> Nil Then
                Begin
                    For J := 0 To Prj.DM_LogicalDocumentCount - 1 Do
                    Begin
                        Doc := Prj.DM_LogicalDocuments(J);
                        If Doc <> Nil Then
                        Begin
                            If UpperCase(Doc.DM_DocumentKind) = 'SCHLIB' Then
                            Begin
                                P := Doc.DM_FullPath;

                                // Stale == registered but gone from disk.
                                // Computed stepwise; DelphiScript's parser is
                                // unreliable with compound And/Or conditions.
                                Wanted := True;
                                If CLOSE_ONLY_MISSING_FILES Then
                                    If FileExists(P) Then
                                        Wanted := False;

                                If Wanted Then
                                    If Cands.IndexOf(P) < 0 Then
                                        Cands.Add(P);
                            End;
                        End;
                    End;
                End;
            End;
        End;

        If Cands.Count = 0 Then
        Begin
            ShowMessage('No stale schematic libraries found.' + #13#10#13#10 +
                'Either the cache is clean, or the cached document has been ' +
                'detached from the workspace and the scan cannot see it. ' +
                'In that case run ShowCurrentLibPath while the library is ' +
                'open, put the path in STALE_LIB_PATH, and re-run.');
            Exit;
        End;

        NumClosed := 0;
        Rpt.Add('Stale library candidates: ' + IntToStr(Cands.Count));
        Rpt.Add('');

        For I := 0 To Cands.Count - 1 Do
        Begin
            P := Cands.Strings[I];
            Status := CloseOneDocument(P);
            If Status = 'CLOSED' Then NumClosed := NumClosed + 1;
            Rpt.Add(P);
            Rpt.Add('  -> ' + Status);
            Rpt.Add('');
        End;

        Rpt.Add('---');
        Rpt.Add('Closed: ' + IntToStr(NumClosed));
        If NumClosed > 0 Then
            Rpt.Add('Now create the new library, make it active, run GenerateSymbol.');

        ShowMessage(Rpt.Text);
    Finally
        Cands.Free;
        Rpt.Free;
    End;
End;


// ---------------------------------------------------------------------------
// Symbol construction helpers
// ---------------------------------------------------------------------------
Procedure AddPartRect(PartId, Xmil, Ymil, Wmil, Hmil : Integer);
Var R;
Begin
    R := SchServer.SchObjectFactory(eRectangle, eCreate_GlobalCopy);
    R.OwnerPartId := PartId;
    R.OwnerPartDisplayMode := 0;
    R.Location := Point(MilsToCoord(Xmil), MilsToCoord(Ymil - Hmil));
    R.Corner := Point(MilsToCoord(Xmil + Wmil), MilsToCoord(Ymil));
    R.LineWidth := eSmall;
    R.IsSolid := True;
    R.AreaColor := $00E7FFFF;
    R.Color := $00000080;
    Comp.AddSchObject(R);
End;

Procedure AddPartPin(PartId, Xmil, Ymil : Integer; Desig, Nm : String);
Var Pin;
Begin
    Pin := SchServer.SchObjectFactory(ePin, eCreate_GlobalCopy);
    Pin.OwnerPartId := PartId;
    Pin.OwnerPartDisplayMode := 0;
    Pin.Orientation := eRotate0;
    Pin.Location := Point(MilsToCoord(Xmil - 300), MilsToCoord(Ymil));
    Pin.PinLength := MilsToCoord(300);
    Pin.Designator := Desig;
    Pin.Name := Nm;
    Pin.ShowName := True;
    Pin.ShowDesignator := True;
    Pin.Electrical := eElectricPassive;
    Comp.AddSchObject(Pin);
End;


Procedure BuildPart1;
Begin
    AddPartRect(1, 0, 0, 1200, 17800);
    AddPartPin(1, 0, -100, 'T25', 'VDD08');
    AddPartPin(1, 0, -200, 'T28', 'VDD08');
    AddPartPin(1, 0, -300, 'T63', 'VDD08');
    AddPartPin(1, 0, -400, 'B24', 'VDD08');
    AddPartPin(1, 0, -500, 'B27', 'VDD08');
    AddPartPin(1, 0, -600, 'L31', 'VDD08');
    AddPartPin(1, 0, -700, 'R34', 'VDD08');
    AddPartPin(1, 0, -800, 'B42', 'VDD08BIAS<0>');
    AddPartPin(1, 0, -900, 'B43', 'VDD08BIAS<0>');
    AddPartPin(1, 0, -1000, 'B8', 'VDD08BIAS<1>');
    AddPartPin(1, 0, -1100, 'B9', 'VDD08BIAS<1>');
    AddPartPin(1, 0, -1200, 'T2', 'VDD08D');
    AddPartPin(1, 0, -1300, 'T9', 'VDD08D');
    AddPartPin(1, 0, -1400, 'T26', 'VDD08D');
    AddPartPin(1, 0, -1500, 'T35', 'VDD08D');
    AddPartPin(1, 0, -1600, 'T44', 'VDD08D');
    AddPartPin(1, 0, -1700, 'T53', 'VDD08D');
    AddPartPin(1, 0, -1800, 'T62', 'VDD08D');
    AddPartPin(1, 0, -1900, 'T75', 'VDD08D');
    AddPartPin(1, 0, -2000, 'B25', 'VDD08D');
    AddPartPin(1, 0, -2100, 'L11', 'VDD08D');
    AddPartPin(1, 0, -2200, 'L18', 'VDD08D');
    AddPartPin(1, 0, -2300, 'L19', 'VDD08D');
    AddPartPin(1, 0, -2400, 'L23', 'VDD08D');
    AddPartPin(1, 0, -2500, 'L24', 'VDD08D');
    AddPartPin(1, 0, -2600, 'L25', 'VDD08D');
    AddPartPin(1, 0, -2700, 'R31', 'VDD08D');
    AddPartPin(1, 0, -2800, 'T37', 'VDD08DLL<0>');
    AddPartPin(1, 0, -2900, 'T42', 'VDD08DLL<1>');
    AddPartPin(1, 0, -3000, 'B36', 'VDD08DLL<2>');
    AddPartPin(1, 0, -3100, 'B41', 'VDD08DLL<3>');
    AddPartPin(1, 0, -3200, 'B15', 'VDD08DLL<4>');
    AddPartPin(1, 0, -3300, 'B10', 'VDD08DLL<5>');
    AddPartPin(1, 0, -3400, 'T13', 'VDD08DLL<6>');
    AddPartPin(1, 0, -3500, 'T11', 'VDD08DLL<7>');
    AddPartPin(1, 0, -3600, 'R9', 'VDD08LED');
    AddPartPin(1, 0, -3700, 'R15', 'VDD08LED');
    AddPartPin(1, 0, -3800, 'R18', 'VDD08LED');
    AddPartPin(1, 0, -3900, 'R24', 'VDD08LED');
    AddPartPin(1, 0, -4000, 'T8', 'VDD08PA');
    AddPartPin(1, 0, -4100, 'T17', 'VDD08PA');
    AddPartPin(1, 0, -4200, 'T20', 'VDD08PA');
    AddPartPin(1, 0, -4300, 'T27', 'VDD08PA');
    AddPartPin(1, 0, -4400, 'T33', 'VDD08PA');
    AddPartPin(1, 0, -4500, 'T36', 'VDD08PA');
    AddPartPin(1, 0, -4600, 'B16', 'VDD08PA');
    AddPartPin(1, 0, -4700, 'B19', 'VDD08PA');
    AddPartPin(1, 0, -4800, 'B26', 'VDD08PA');
    AddPartPin(1, 0, -4900, 'B32', 'VDD08PA');
    AddPartPin(1, 0, -5000, 'B35', 'VDD08PA');
    AddPartPin(1, 0, -5100, 'L32', 'VDD08PA');
    AddPartPin(1, 0, -5200, 'L33', 'VDD08PA');
    AddPartPin(1, 0, -5300, 'L34', 'VDD08PA');
    AddPartPin(1, 0, -5400, 'T23', 'VDD08TIA');
    AddPartPin(1, 0, -5500, 'T30', 'VDD08TIA');
    AddPartPin(1, 0, -5600, 'B22', 'VDD08TIA');
    AddPartPin(1, 0, -5700, 'B29', 'VDD08TIA');
    AddPartPin(1, 0, -5800, 'T45', 'VDD12LED');
    AddPartPin(1, 0, -5900, 'T51', 'VDD12LED');
    AddPartPin(1, 0, -6000, 'T57', 'VDD12LED');
    AddPartPin(1, 0, -6100, 'B44', 'VDD12LED');
    AddPartPin(1, 0, -6200, 'B50', 'VDD12LED');
    AddPartPin(1, 0, -6300, 'B51', 'VDD12LED');
    AddPartPin(1, 0, -6400, 'B56', 'VDD12LED');
    AddPartPin(1, 0, -6500, 'B57', 'VDD12LED');
    AddPartPin(1, 0, -6600, 'R10', 'VDD12LED');
    AddPartPin(1, 0, -6700, 'R16', 'VDD12LED');
    AddPartPin(1, 0, -6800, 'R19', 'VDD12LED');
    AddPartPin(1, 0, -6900, 'R25', 'VDD12LED');
    AddPartPin(1, 0, -7000, 'L30', 'VDD18A');
    AddPartPin(1, 0, -7100, 'L21', 'VDD18B');
    AddPartPin(1, 0, -7200, 'R39', 'VDD18C');
    AddPartPin(1, 0, -7300, 'B6', 'VDD18D');
    AddPartPin(1, 0, -7400, 'T64', 'VDD18E');
    AddPartPin(1, 0, -7500, 'B52', 'VDD18LED');
    AddPartPin(1, 0, -7600, 'R5', 'VDD18LED');
    AddPartPin(1, 0, -7700, 'R29', 'VDD18LED');
    AddPartPin(1, 0, -7800, 'T38', 'VDD18PLL<0>');
    AddPartPin(1, 0, -7900, 'T41', 'VDD18PLL<1>');
    AddPartPin(1, 0, -8000, 'B37', 'VDD18PLL<2>');
    AddPartPin(1, 0, -8100, 'B40', 'VDD18PLL<3>');
    AddPartPin(1, 0, -8200, 'B14', 'VDD18PLL<4>');
    AddPartPin(1, 0, -8300, 'B11', 'VDD18PLL<5>');
    AddPartPin(1, 0, -8400, 'T15', 'VDD18PLL<6>');
    AddPartPin(1, 0, -8500, 'T12', 'VDD18PLL<7>');
    AddPartPin(1, 0, -8600, 'B33', 'VDD18_BG<0>');
    AddPartPin(1, 0, -8700, 'B18', 'VDD18_BG<1>');
    AddPartPin(1, 0, -8800, 'T48', 'VDD50LED');
    AddPartPin(1, 0, -8900, 'T54', 'VDD50LED');
    AddPartPin(1, 0, -9000, 'T60', 'VDD50LED');
    AddPartPin(1, 0, -9100, 'B47', 'VDD50LED');
    AddPartPin(1, 0, -9200, 'B53', 'VDD50LED');
    AddPartPin(1, 0, -9300, 'B59', 'VDD50LED');
    AddPartPin(1, 0, -9400, 'B60', 'VDD50LED');
    AddPartPin(1, 0, -9500, 'B61', 'VDD50LED');
    AddPartPin(1, 0, -9600, 'R6', 'VDD50LED');
    AddPartPin(1, 0, -9700, 'R7', 'VDD50LED');
    AddPartPin(1, 0, -9800, 'R13', 'VDD50LED');
    AddPartPin(1, 0, -9900, 'R22', 'VDD50LED');
    AddPartPin(1, 0, -10000, 'R28', 'VDD50LED');
    AddPartPin(1, 0, -10100, 'T19', 'VDD50PD');
    AddPartPin(1, 0, -10200, 'L39', 'VDDPST');
    AddPartPin(1, 0, -10300, 'R45', 'VDDPST');
    AddPartPin(1, 0, -10400, 'T1', 'VSS');
    AddPartPin(1, 0, -10500, 'T3', 'VSS');
    AddPartPin(1, 0, -10600, 'T5', 'VSS');
    AddPartPin(1, 0, -10700, 'T6', 'VSS');
    AddPartPin(1, 0, -10800, 'T14', 'VSS');
    AddPartPin(1, 0, -10900, 'T18', 'VSS');
    AddPartPin(1, 0, -11000, 'T21', 'VSS');
    AddPartPin(1, 0, -11100, 'T32', 'VSS');
    AddPartPin(1, 0, -11200, 'T39', 'VSS');
    AddPartPin(1, 0, -11300, 'T71', 'VSS');
    AddPartPin(1, 0, -11400, 'T72', 'VSS');
    AddPartPin(1, 0, -11500, 'T74', 'VSS');
    AddPartPin(1, 0, -11600, 'T76', 'VSS');
    AddPartPin(1, 0, -11700, 'B1', 'VSS');
    AddPartPin(1, 0, -11800, 'B3', 'VSS');
    AddPartPin(1, 0, -11900, 'B12', 'VSS');
    AddPartPin(1, 0, -12000, 'B13', 'VSS');
    AddPartPin(1, 0, -12100, 'B17', 'VSS');
    AddPartPin(1, 0, -12200, 'B20', 'VSS');
    AddPartPin(1, 0, -12300, 'B31', 'VSS');
    AddPartPin(1, 0, -12400, 'B34', 'VSS');
    AddPartPin(1, 0, -12500, 'B38', 'VSS');
    AddPartPin(1, 0, -12600, 'L1', 'VSS');
    AddPartPin(1, 0, -12700, 'L6', 'VSS');
    AddPartPin(1, 0, -12800, 'L8', 'VSS');
    AddPartPin(1, 0, -12900, 'L9', 'VSS');
    AddPartPin(1, 0, -13000, 'L10', 'VSS');
    AddPartPin(1, 0, -13100, 'L12', 'VSS');
    AddPartPin(1, 0, -13200, 'L13', 'VSS');
    AddPartPin(1, 0, -13300, 'L14', 'VSS');
    AddPartPin(1, 0, -13400, 'L17', 'VSS');
    AddPartPin(1, 0, -13500, 'L26', 'VSS');
    AddPartPin(1, 0, -13600, 'L27', 'VSS');
    AddPartPin(1, 0, -13700, 'L38', 'VSS');
    AddPartPin(1, 0, -13800, 'L40', 'VSS');
    AddPartPin(1, 0, -13900, 'R32', 'VSS');
    AddPartPin(1, 0, -14000, 'R38', 'VSS');
    AddPartPin(1, 0, -14100, 'R41', 'VSS');
    AddPartPin(1, 0, -14200, 'R43', 'VSS');
    AddPartPin(1, 0, -14300, 'R44', 'VSS');
    AddPartPin(1, 0, -14400, 'R46', 'VSS');
    AddPartPin(1, 0, -14500, 'T47', 'VSSLED');
    AddPartPin(1, 0, -14600, 'T50', 'VSSLED');
    AddPartPin(1, 0, -14700, 'T56', 'VSSLED');
    AddPartPin(1, 0, -14800, 'T59', 'VSSLED');
    AddPartPin(1, 0, -14900, 'B46', 'VSSLED');
    AddPartPin(1, 0, -15000, 'B48', 'VSSLED');
    AddPartPin(1, 0, -15100, 'B49', 'VSSLED');
    AddPartPin(1, 0, -15200, 'B54', 'VSSLED');
    AddPartPin(1, 0, -15300, 'B55', 'VSSLED');
    AddPartPin(1, 0, -15400, 'B58', 'VSSLED');
    AddPartPin(1, 0, -15500, 'B62', 'VSSLED');
    AddPartPin(1, 0, -15600, 'B63', 'VSSLED');
    AddPartPin(1, 0, -15700, 'B64', 'VSSLED');
    AddPartPin(1, 0, -15800, 'B65', 'VSSLED');
    AddPartPin(1, 0, -15900, 'B66', 'VSSLED');
    AddPartPin(1, 0, -16000, 'R1', 'VSSLED');
    AddPartPin(1, 0, -16100, 'R2', 'VSSLED');
    AddPartPin(1, 0, -16200, 'R3', 'VSSLED');
    AddPartPin(1, 0, -16300, 'R4', 'VSSLED');
    AddPartPin(1, 0, -16400, 'R8', 'VSSLED');
    AddPartPin(1, 0, -16500, 'R11', 'VSSLED');
    AddPartPin(1, 0, -16600, 'R12', 'VSSLED');
    AddPartPin(1, 0, -16700, 'R14', 'VSSLED');
    AddPartPin(1, 0, -16800, 'R17', 'VSSLED');
    AddPartPin(1, 0, -16900, 'R20', 'VSSLED');
    AddPartPin(1, 0, -17000, 'R23', 'VSSLED');
    AddPartPin(1, 0, -17100, 'R26', 'VSSLED');
    AddPartPin(1, 0, -17200, 'L36', 'VSSPST');
    AddPartPin(1, 0, -17300, 'R42', 'VSSPST');
    AddPartPin(1, 0, -17400, 'T24', 'VSSTIA');
    AddPartPin(1, 0, -17500, 'T29', 'VSSTIA');
    AddPartPin(1, 0, -17600, 'B23', 'VSSTIA');
    AddPartPin(1, 0, -17700, 'B28', 'VSSTIA');
End;

Procedure BuildPart2;
Begin
    AddPartRect(2, 0, 0, 1200, 2300);
    AddPartPin(2, 0, -100, 'L7', 'CHIP_ID<0>');
    AddPartPin(2, 0, -200, 'L5', 'CHIP_ID<1>');
    AddPartPin(2, 0, -300, 'L3', 'CHIP_ID<2>');
    AddPartPin(2, 0, -400, 'T34', 'CSB');
    AddPartPin(2, 0, -500, 'T58', 'DFT_SCAN_SDI<1>');
    AddPartPin(2, 0, -600, 'T61', 'DFT_SCAN_SDI<2>');
    AddPartPin(2, 0, -700, 'T73', 'DFT_SCN_SDO<1>');
    AddPartPin(2, 0, -800, 'T70', 'DFT_SCN_SDO<2>');
    AddPartPin(2, 0, -900, 'T67', 'F');
    AddPartPin(2, 0, -1000, 'T16', 'LB_PCLK');
    AddPartPin(2, 0, -1100, 'T22', 'RESET_N');
    AddPartPin(2, 0, -1200, 'T55', 'SCAN_CLK');
    AddPartPin(2, 0, -1300, 'T52', 'SCAN_EN');
    AddPartPin(2, 0, -1400, 'T40', 'SCAN_MODE');
    AddPartPin(2, 0, -1500, 'T46', 'SCAN_SAFE_MODE');
    AddPartPin(2, 0, -1600, 'T43', 'SCK');
    AddPartPin(2, 0, -1700, 'T10', 'SCL');
    AddPartPin(2, 0, -1800, 'T7', 'SDA');
    AddPartPin(2, 0, -1900, 'T31', 'SDI');
    AddPartPin(2, 0, -2000, 'T4', 'SEL_APB_SPI_N');
    AddPartPin(2, 0, -2100, 'L4', 'V3_CHIP ID<0>');
    AddPartPin(2, 0, -2200, 'L2', 'V3_CHIP ID<1>');
End;

Procedure BuildPart3;
Begin
    AddPartRect(3, 0, 0, 1200, 2000);
    AddPartPin(3, 0, -100, 'R40', 'LED_I0_CURRENT');
    AddPartPin(3, 0, -200, 'R33', 'LED_I0_SNS');
    AddPartPin(3, 0, -300, 'R36', 'LED_I1_SNS');
    AddPartPin(3, 0, -400, 'T65', 'REXT1');
    AddPartPin(3, 0, -500, 'T68', 'REXT2');
    AddPartPin(3, 0, -600, 'B5', 'RSSI_L');
    AddPartPin(3, 0, -700, 'B7', 'RSSI_R');
    AddPartPin(3, 0, -800, 'L28', 'VATB_DLL');
    AddPartPin(3, 0, -900, 'T69', 'VATB_LED0');
    AddPartPin(3, 0, -1000, 'T66', 'VATB_LED1');
    AddPartPin(3, 0, -1100, 'L22', 'VATB_RSSI0');
    AddPartPin(3, 0, -1200, 'L20', 'VATB_RSSI1');
    AddPartPin(3, 0, -1300, 'L29', 'VATB_TIA');
    AddPartPin(3, 0, -1400, 'R27', 'VDD08D_SNS');
    AddPartPin(3, 0, -1500, 'B21', 'VDD08PA_SNS');
    AddPartPin(3, 0, -1600, 'B30', 'VDD08TIA_SNS');
    AddPartPin(3, 0, -1700, 'T49', 'VDD50LED_SNS');
    AddPartPin(3, 0, -1800, 'R21', 'VDDDRVLED_SNS');
    AddPartPin(3, 0, -1900, 'R30', 'VDDLED_SNS');
End;

Procedure BuildPart4;
Begin
    AddPartRect(4, 0, 0, 1200, 700);
    AddPartPin(4, 0, -100, 'B45', 'CLKEXTP<0>');
    AddPartPin(4, 0, -200, 'B39', 'CLKEXTM<0>');
    AddPartPin(4, 0, -300, 'L35', 'CLKEXTP<1>');
    AddPartPin(4, 0, -400, 'L37', 'CLKEXTM<1>');
    AddPartPin(4, 0, -500, 'B2', 'CLKOUTP_MUX');
    AddPartPin(4, 0, -600, 'B4', 'CLKOUTN_MUX');
End;

Procedure BuildPart5;
Begin
    AddPartRect(5, 0, 0, 1200, 500);
    AddPartPin(5, 0, -100, 'L16', 'TEST_DLL_DESKEW_CKOUT');
    AddPartPin(5, 0, -200, 'R35', 'TEST_LED_STRB0_CKOUT');
    AddPartPin(5, 0, -300, 'L15', 'TEST_PLL4_CKOUT');
    AddPartPin(5, 0, -400, 'R37', 'TEST_TX_CKOUT');
End;


// ---------------------------------------------------------------------------
// Idempotency: strip any pre-existing copies of COMP_NAME from the library.
//
// The iterator is re-created after every removal. Mutating a library while an
// Altium iterator is live over it is unreliable -- the "cache Next, then
// remove" pattern still leaves the iterator pointing into a container that
// changed underneath it, which silently skips entries and lets a copy survive.
// ---------------------------------------------------------------------------
Function RemoveExisting : Integer;
Var
    It     : ISch_Iterator;
    Cmp    : ISch_Component;
    Victim : ISch_Component;
    Guard  : Integer;
    Done   : Boolean;
Begin
    Result := 0;
    Guard  := 0;

    Repeat
        Victim := Nil;

        It := Lib.SchLibIterator_Create;
        If It = Nil Then Break;
        Try
            It.AddFilter_ObjectSet(MkSet(eSchComponent));
            Cmp := It.FirstSchObject;
            While Cmp <> Nil Do
            Begin
                If Cmp.LibReference = COMP_NAME Then
                Begin
                    Victim := Cmp;
                    Break;
                End;
                Cmp := It.NextSchObject;
            End;
        Finally
            Lib.SchIterator_Destroy(It);
        End;

        If Victim <> Nil Then
        Begin
            Lib.RemoveSchComponent(Victim);
            Result := Result + 1;
        End;

        Guard := Guard + 1;

        // Loop exit computed stepwise rather than as a compound Or.
        Done := False;
        If Victim = Nil Then Done := True;
        If Guard > 500 Then Done := True;
    Until Done;
End;


// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------
Procedure GenerateSymbol;
Var
    Impl;
    Removed : Integer;
    Warn    : String;
Begin
    If SchServer = Nil Then
    Begin
        ShowMessage('SchServer is nil -- the schematic editor is not loaded.');
        Exit;
    End;

    Lib := SchServer.GetCurrentSchDocument;
    If Lib = Nil Then
    Begin
        ShowMessage('No schematic library open. Create one first: ' +
            'File > New > Library > Schematic Library, make it active, then run again.');
        Exit;
    End;

    // Guard against a .SchDoc being focused instead of a .SchLib --
    // AddSchComponent on a plain sheet fails in confusing ways.
    If Lib.ObjectID <> eSchLib Then
    Begin
        ShowMessage('The active document is not a schematic library. ' +
            'Focus the .SchLib tab and run again.');
        Exit;
    End;

    SchServer.ProcessControl.PreProcess(Lib, '');
    Try
        Removed := RemoveExisting;

        Comp := SchServer.SchObjectFactory(eSchComponent, eCreate_GlobalCopy);
        Comp.LibReference := COMP_NAME;
        Comp.ComponentDescription := 'Probe card -- one part per net class';
        Comp.Designator.Text := 'PC?';
        Comp.PartCount := 5;
        Comp.DisplayMode := 0;

        BuildPart1;
        BuildPart2;
        BuildPart3;
        BuildPart4;
        BuildPart5;

        Impl := Comp.AddSchImplementation;
        Impl.ModelName := FP_NAME;
        Impl.ModelType := 'PCBLIB';
        Impl.IsCurrent := True;

        Lib.AddSchComponent(Comp);
        Lib.CurrentSchComponent := Comp;

        // Register the new component so the SCH Library panel refreshes
        // instead of showing a stale component list.
        SchServer.RobotManager.SendMessage(Lib.I_ObjectAddress, c_BroadCast,
            SCHM_PrimitiveRegistration, Comp.I_ObjectAddress);

        Comp.GraphicallyInvalidate;
    Finally
        SchServer.ProcessControl.PostProcess(Lib, '');
    End;

    If Removed > 0 Then
        Warn := #13#10#13#10 +
            'Pre-existing copies were found and removed. If you created this ' +
            'library from scratch just now, Altium handed you a CACHED ' +
            'document -- that is your duplicate source. Run ListOpenDocuments ' +
            'and CloseStaleLibrary before the next run.'
    Else
        Warn := '';

    ShowMessage('Component ' + COMP_NAME + ' built in ' + Lib.DocumentName +
        #13#10 + 'Pre-existing copies removed: ' + IntToStr(Removed) +
        #13#10#13#10 + 'Save the .SchLib.' + Warn);
End;
