// Auto-generated by auto_probe_pcb.py -- Altium schematic DelphiScript.
// Build a blank schematic first: File > New > Schematic, make that tab the
// ACTIVE document, then File > Run Script... and run GenerateSchematic.
// Produces one vertical block per net class; each pin is one probe land,
// pin designator = land id (B1, L5...), pin name = the die signal.
// A standalone sheet -- drop it into your project and add components freely.

Var
    Doc : ISch_Document;

// --- one rectangular net-class block, pins stubbed out to the left.
// --- Scripted Sch primitives MUST carry OwnerPartId/OwnerPartDisplayMode
// --- matching the component's CurrentPartID/DisplayMode, or Altium drops
// --- them onto the component origin instead of their set locations.
Function NewBlock(Xmil, Ymil, Wmil, Hmil : Integer; Comment : String) : ISch_Component;
Var Comp, R;
Begin
    Comp := SchServer.SchObjectFactory(eSchComponent, eCreate_GlobalCopy);
    Comp.Location := Point(MilsToCoord(Xmil), MilsToCoord(Ymil));
    Comp.CurrentPartID := 1;
    Comp.DisplayMode := 0;
    Comp.Designator.Text := Comment;
    Comp.Designator.IsHidden := False;
    Comp.Comment.Text := Comment;
    Comp.Comment.IsHidden := True;
    R := SchServer.SchObjectFactory(eRectangle, eCreate_GlobalCopy);
    R.OwnerPartId := Comp.CurrentPartID;
    R.OwnerPartDisplayMode := Comp.DisplayMode;
    R.Location := Point(MilsToCoord(Xmil), MilsToCoord(Ymil - Hmil));
    R.Corner := Point(MilsToCoord(Xmil + Wmil), MilsToCoord(Ymil));
    R.LineWidth := eSmall;
    R.IsSolid := True;
    R.AreaColor := $00E7FFFF;
    R.Color := $00000080;
    Comp.AddSchObject(R);
    Result := Comp;
End;

// --- add one probe land as a left-side pin on the block. Xmil is the block's
// --- left edge; the pin hot-spot sits one PinLength further left so the stub
// --- sticks out. Left-side pins use eRotate0 (pin points right into the body).
Procedure AddPin(Comp : ISch_Component; Xmil, Ymil : Integer; Desig, Nm : String);
Var Pin;
Begin
    Pin := SchServer.SchObjectFactory(ePin, eCreate_GlobalCopy);
    Pin.OwnerPartId := Comp.CurrentPartID;
    Pin.OwnerPartDisplayMode := Comp.DisplayMode;
    Pin.Orientation := eRotate0;
    Pin.Location := Point(MilsToCoord(Xmil - 300), MilsToCoord(Ymil));
    Pin.PinLength := MilsToCoord(300);
    Pin.Designator := Desig;
    Pin.Name := Nm;
    Pin.ShowName := True;
    Pin.ShowDesignator := True;
    Pin.Electrical := eElectricPassive;
    Comp.AddSchObject(Pin);
End;

// --- free-text title above a block (full net-class name; may contain spaces).
Procedure AddTitle(Xmil, Ymil : Integer; S : String);
Var T;
Begin
    T := SchServer.SchObjectFactory(eLabel, eCreate_GlobalCopy);
    T.Location := Point(MilsToCoord(Xmil), MilsToCoord(Ymil));
    T.Text := S;
    T.FontID := 1;
    Doc.RegisterSchObjectInContainer(T);
    SchServer.RobotManager.SendMessage(Doc.I_ObjectAddress, c_BroadCast,
        SCHM_PrimitiveRegistration, T.I_ObjectAddress);
End;

Procedure Commit(Comp : ISch_Component);
Begin
    Doc.RegisterSchObjectInContainer(Comp);
    SchServer.RobotManager.SendMessage(Doc.I_ObjectAddress, c_BroadCast,
        SCHM_PrimitiveRegistration, Comp.I_ObjectAddress);
End;


Procedure BuildBlock0;
Var C;
Begin
    AddTitle(1000, -700, 'Power');
    C := NewBlock(1000, -1000, 1200, 17800, 'POWER');
    AddPin(C, 1000, -1100, 'T25', 'VDD08');
    AddPin(C, 1000, -1200, 'T28', 'VDD08');
    AddPin(C, 1000, -1300, 'T63', 'VDD08');
    AddPin(C, 1000, -1400, 'B24', 'VDD08');
    AddPin(C, 1000, -1500, 'B27', 'VDD08');
    AddPin(C, 1000, -1600, 'L31', 'VDD08');
    AddPin(C, 1000, -1700, 'R34', 'VDD08');
    AddPin(C, 1000, -1800, 'B42', 'VDD08BIAS<0>');
    AddPin(C, 1000, -1900, 'B43', 'VDD08BIAS<0>');
    AddPin(C, 1000, -2000, 'B8', 'VDD08BIAS<1>');
    AddPin(C, 1000, -2100, 'B9', 'VDD08BIAS<1>');
    AddPin(C, 1000, -2200, 'T2', 'VDD08D');
    AddPin(C, 1000, -2300, 'T9', 'VDD08D');
    AddPin(C, 1000, -2400, 'T26', 'VDD08D');
    AddPin(C, 1000, -2500, 'T35', 'VDD08D');
    AddPin(C, 1000, -2600, 'T44', 'VDD08D');
    AddPin(C, 1000, -2700, 'T53', 'VDD08D');
    AddPin(C, 1000, -2800, 'T62', 'VDD08D');
    AddPin(C, 1000, -2900, 'T75', 'VDD08D');
    AddPin(C, 1000, -3000, 'B25', 'VDD08D');
    AddPin(C, 1000, -3100, 'L11', 'VDD08D');
    AddPin(C, 1000, -3200, 'L18', 'VDD08D');
    AddPin(C, 1000, -3300, 'L19', 'VDD08D');
    AddPin(C, 1000, -3400, 'L23', 'VDD08D');
    AddPin(C, 1000, -3500, 'L24', 'VDD08D');
    AddPin(C, 1000, -3600, 'L25', 'VDD08D');
    AddPin(C, 1000, -3700, 'R31', 'VDD08D');
    AddPin(C, 1000, -3800, 'T37', 'VDD08DLL<0>');
    AddPin(C, 1000, -3900, 'T42', 'VDD08DLL<1>');
    AddPin(C, 1000, -4000, 'B36', 'VDD08DLL<2>');
    AddPin(C, 1000, -4100, 'B41', 'VDD08DLL<3>');
    AddPin(C, 1000, -4200, 'B15', 'VDD08DLL<4>');
    AddPin(C, 1000, -4300, 'B10', 'VDD08DLL<5>');
    AddPin(C, 1000, -4400, 'T13', 'VDD08DLL<6>');
    AddPin(C, 1000, -4500, 'T11', 'VDD08DLL<7>');
    AddPin(C, 1000, -4600, 'R9', 'VDD08LED');
    AddPin(C, 1000, -4700, 'R15', 'VDD08LED');
    AddPin(C, 1000, -4800, 'R18', 'VDD08LED');
    AddPin(C, 1000, -4900, 'R24', 'VDD08LED');
    AddPin(C, 1000, -5000, 'T8', 'VDD08PA');
    AddPin(C, 1000, -5100, 'T17', 'VDD08PA');
    AddPin(C, 1000, -5200, 'T20', 'VDD08PA');
    AddPin(C, 1000, -5300, 'T27', 'VDD08PA');
    AddPin(C, 1000, -5400, 'T33', 'VDD08PA');
    AddPin(C, 1000, -5500, 'T36', 'VDD08PA');
    AddPin(C, 1000, -5600, 'B16', 'VDD08PA');
    AddPin(C, 1000, -5700, 'B19', 'VDD08PA');
    AddPin(C, 1000, -5800, 'B26', 'VDD08PA');
    AddPin(C, 1000, -5900, 'B32', 'VDD08PA');
    AddPin(C, 1000, -6000, 'B35', 'VDD08PA');
    AddPin(C, 1000, -6100, 'L32', 'VDD08PA');
    AddPin(C, 1000, -6200, 'L33', 'VDD08PA');
    AddPin(C, 1000, -6300, 'L34', 'VDD08PA');
    AddPin(C, 1000, -6400, 'T23', 'VDD08TIA');
    AddPin(C, 1000, -6500, 'T30', 'VDD08TIA');
    AddPin(C, 1000, -6600, 'B22', 'VDD08TIA');
    AddPin(C, 1000, -6700, 'B29', 'VDD08TIA');
    AddPin(C, 1000, -6800, 'T45', 'VDD12LED');
    AddPin(C, 1000, -6900, 'T51', 'VDD12LED');
    AddPin(C, 1000, -7000, 'T57', 'VDD12LED');
    AddPin(C, 1000, -7100, 'B44', 'VDD12LED');
    AddPin(C, 1000, -7200, 'B50', 'VDD12LED');
    AddPin(C, 1000, -7300, 'B51', 'VDD12LED');
    AddPin(C, 1000, -7400, 'B56', 'VDD12LED');
    AddPin(C, 1000, -7500, 'B57', 'VDD12LED');
    AddPin(C, 1000, -7600, 'R10', 'VDD12LED');
    AddPin(C, 1000, -7700, 'R16', 'VDD12LED');
    AddPin(C, 1000, -7800, 'R19', 'VDD12LED');
    AddPin(C, 1000, -7900, 'R25', 'VDD12LED');
    AddPin(C, 1000, -8000, 'L30', 'VDD18A');
    AddPin(C, 1000, -8100, 'L21', 'VDD18B');
    AddPin(C, 1000, -8200, 'R39', 'VDD18C');
    AddPin(C, 1000, -8300, 'B6', 'VDD18D');
    AddPin(C, 1000, -8400, 'T64', 'VDD18E');
    AddPin(C, 1000, -8500, 'B52', 'VDD18LED');
    AddPin(C, 1000, -8600, 'R5', 'VDD18LED');
    AddPin(C, 1000, -8700, 'R29', 'VDD18LED');
    AddPin(C, 1000, -8800, 'T38', 'VDD18PLL<0>');
    AddPin(C, 1000, -8900, 'T41', 'VDD18PLL<1>');
    AddPin(C, 1000, -9000, 'B37', 'VDD18PLL<2>');
    AddPin(C, 1000, -9100, 'B40', 'VDD18PLL<3>');
    AddPin(C, 1000, -9200, 'B14', 'VDD18PLL<4>');
    AddPin(C, 1000, -9300, 'B11', 'VDD18PLL<5>');
    AddPin(C, 1000, -9400, 'T15', 'VDD18PLL<6>');
    AddPin(C, 1000, -9500, 'T12', 'VDD18PLL<7>');
    AddPin(C, 1000, -9600, 'B33', 'VDD18_BG<0>');
    AddPin(C, 1000, -9700, 'B18', 'VDD18_BG<1>');
    AddPin(C, 1000, -9800, 'T48', 'VDD50LED');
    AddPin(C, 1000, -9900, 'T54', 'VDD50LED');
    AddPin(C, 1000, -10000, 'T60', 'VDD50LED');
    AddPin(C, 1000, -10100, 'B47', 'VDD50LED');
    AddPin(C, 1000, -10200, 'B53', 'VDD50LED');
    AddPin(C, 1000, -10300, 'B59', 'VDD50LED');
    AddPin(C, 1000, -10400, 'B60', 'VDD50LED');
    AddPin(C, 1000, -10500, 'B61', 'VDD50LED');
    AddPin(C, 1000, -10600, 'R6', 'VDD50LED');
    AddPin(C, 1000, -10700, 'R7', 'VDD50LED');
    AddPin(C, 1000, -10800, 'R13', 'VDD50LED');
    AddPin(C, 1000, -10900, 'R22', 'VDD50LED');
    AddPin(C, 1000, -11000, 'R28', 'VDD50LED');
    AddPin(C, 1000, -11100, 'T19', 'VDD50PD');
    AddPin(C, 1000, -11200, 'L39', 'VDDPST');
    AddPin(C, 1000, -11300, 'R45', 'VDDPST');
    AddPin(C, 1000, -11400, 'T1', 'VSS');
    AddPin(C, 1000, -11500, 'T3', 'VSS');
    AddPin(C, 1000, -11600, 'T5', 'VSS');
    AddPin(C, 1000, -11700, 'T6', 'VSS');
    AddPin(C, 1000, -11800, 'T14', 'VSS');
    AddPin(C, 1000, -11900, 'T18', 'VSS');
    AddPin(C, 1000, -12000, 'T21', 'VSS');
    AddPin(C, 1000, -12100, 'T32', 'VSS');
    AddPin(C, 1000, -12200, 'T39', 'VSS');
    AddPin(C, 1000, -12300, 'T71', 'VSS');
    AddPin(C, 1000, -12400, 'T72', 'VSS');
    AddPin(C, 1000, -12500, 'T74', 'VSS');
    AddPin(C, 1000, -12600, 'T76', 'VSS');
    AddPin(C, 1000, -12700, 'B1', 'VSS');
    AddPin(C, 1000, -12800, 'B3', 'VSS');
    AddPin(C, 1000, -12900, 'B12', 'VSS');
    AddPin(C, 1000, -13000, 'B13', 'VSS');
    AddPin(C, 1000, -13100, 'B17', 'VSS');
    AddPin(C, 1000, -13200, 'B20', 'VSS');
    AddPin(C, 1000, -13300, 'B31', 'VSS');
    AddPin(C, 1000, -13400, 'B34', 'VSS');
    AddPin(C, 1000, -13500, 'B38', 'VSS');
    AddPin(C, 1000, -13600, 'L1', 'VSS');
    AddPin(C, 1000, -13700, 'L6', 'VSS');
    AddPin(C, 1000, -13800, 'L8', 'VSS');
    AddPin(C, 1000, -13900, 'L9', 'VSS');
    AddPin(C, 1000, -14000, 'L10', 'VSS');
    AddPin(C, 1000, -14100, 'L12', 'VSS');
    AddPin(C, 1000, -14200, 'L13', 'VSS');
    AddPin(C, 1000, -14300, 'L14', 'VSS');
    AddPin(C, 1000, -14400, 'L17', 'VSS');
    AddPin(C, 1000, -14500, 'L26', 'VSS');
    AddPin(C, 1000, -14600, 'L27', 'VSS');
    AddPin(C, 1000, -14700, 'L38', 'VSS');
    AddPin(C, 1000, -14800, 'L40', 'VSS');
    AddPin(C, 1000, -14900, 'R32', 'VSS');
    AddPin(C, 1000, -15000, 'R38', 'VSS');
    AddPin(C, 1000, -15100, 'R41', 'VSS');
    AddPin(C, 1000, -15200, 'R43', 'VSS');
    AddPin(C, 1000, -15300, 'R44', 'VSS');
    AddPin(C, 1000, -15400, 'R46', 'VSS');
    AddPin(C, 1000, -15500, 'T47', 'VSSLED');
    AddPin(C, 1000, -15600, 'T50', 'VSSLED');
    AddPin(C, 1000, -15700, 'T56', 'VSSLED');
    AddPin(C, 1000, -15800, 'T59', 'VSSLED');
    AddPin(C, 1000, -15900, 'B46', 'VSSLED');
    AddPin(C, 1000, -16000, 'B48', 'VSSLED');
    AddPin(C, 1000, -16100, 'B49', 'VSSLED');
    AddPin(C, 1000, -16200, 'B54', 'VSSLED');
    AddPin(C, 1000, -16300, 'B55', 'VSSLED');
    AddPin(C, 1000, -16400, 'B58', 'VSSLED');
    AddPin(C, 1000, -16500, 'B62', 'VSSLED');
    AddPin(C, 1000, -16600, 'B63', 'VSSLED');
    AddPin(C, 1000, -16700, 'B64', 'VSSLED');
    AddPin(C, 1000, -16800, 'B65', 'VSSLED');
    AddPin(C, 1000, -16900, 'B66', 'VSSLED');
    AddPin(C, 1000, -17000, 'R1', 'VSSLED');
    AddPin(C, 1000, -17100, 'R2', 'VSSLED');
    AddPin(C, 1000, -17200, 'R3', 'VSSLED');
    AddPin(C, 1000, -17300, 'R4', 'VSSLED');
    AddPin(C, 1000, -17400, 'R8', 'VSSLED');
    AddPin(C, 1000, -17500, 'R11', 'VSSLED');
    AddPin(C, 1000, -17600, 'R12', 'VSSLED');
    AddPin(C, 1000, -17700, 'R14', 'VSSLED');
    AddPin(C, 1000, -17800, 'R17', 'VSSLED');
    AddPin(C, 1000, -17900, 'R20', 'VSSLED');
    AddPin(C, 1000, -18000, 'R23', 'VSSLED');
    AddPin(C, 1000, -18100, 'R26', 'VSSLED');
    AddPin(C, 1000, -18200, 'L36', 'VSSPST');
    AddPin(C, 1000, -18300, 'R42', 'VSSPST');
    AddPin(C, 1000, -18400, 'T24', 'VSSTIA');
    AddPin(C, 1000, -18500, 'T29', 'VSSTIA');
    AddPin(C, 1000, -18600, 'B23', 'VSSTIA');
    AddPin(C, 1000, -18700, 'B28', 'VSSTIA');
    Commit(C);
End;

Procedure BuildBlock1;
Var C;
Begin
    AddTitle(3600, -700, 'Digital');
    C := NewBlock(3600, -1000, 1200, 2300, 'DIGITAL');
    AddPin(C, 3600, -1100, 'L7', 'CHIP_ID<0>');
    AddPin(C, 3600, -1200, 'L5', 'CHIP_ID<1>');
    AddPin(C, 3600, -1300, 'L3', 'CHIP_ID<2>');
    AddPin(C, 3600, -1400, 'T34', 'CSB');
    AddPin(C, 3600, -1500, 'T58', 'DFT_SCAN_SDI<1>');
    AddPin(C, 3600, -1600, 'T61', 'DFT_SCAN_SDI<2>');
    AddPin(C, 3600, -1700, 'T73', 'DFT_SCN_SDO<1>');
    AddPin(C, 3600, -1800, 'T70', 'DFT_SCN_SDO<2>');
    AddPin(C, 3600, -1900, 'T67', 'F');
    AddPin(C, 3600, -2000, 'T16', 'LB_PCLK');
    AddPin(C, 3600, -2100, 'T22', 'RESET_N');
    AddPin(C, 3600, -2200, 'T55', 'SCAN_CLK');
    AddPin(C, 3600, -2300, 'T52', 'SCAN_EN');
    AddPin(C, 3600, -2400, 'T40', 'SCAN_MODE');
    AddPin(C, 3600, -2500, 'T46', 'SCAN_SAFE_MODE');
    AddPin(C, 3600, -2600, 'T43', 'SCK');
    AddPin(C, 3600, -2700, 'T10', 'SCL');
    AddPin(C, 3600, -2800, 'T7', 'SDA');
    AddPin(C, 3600, -2900, 'T31', 'SDI');
    AddPin(C, 3600, -3000, 'T4', 'SEL_APB_SPI_N');
    AddPin(C, 3600, -3100, 'L4', 'V3_CHIP ID<0>');
    AddPin(C, 3600, -3200, 'L2', 'V3_CHIP ID<1>');
    Commit(C);
End;

Procedure BuildBlock2;
Var C;
Begin
    AddTitle(6200, -700, 'Analog');
    C := NewBlock(6200, -1000, 1200, 2000, 'ANALOG');
    AddPin(C, 6200, -1100, 'R40', 'LED_I0_CURRENT');
    AddPin(C, 6200, -1200, 'R33', 'LED_I0_SNS');
    AddPin(C, 6200, -1300, 'R36', 'LED_I1_SNS');
    AddPin(C, 6200, -1400, 'T65', 'REXT1');
    AddPin(C, 6200, -1500, 'T68', 'REXT2');
    AddPin(C, 6200, -1600, 'B5', 'RSSI_L');
    AddPin(C, 6200, -1700, 'B7', 'RSSI_R');
    AddPin(C, 6200, -1800, 'L28', 'VATB_DLL');
    AddPin(C, 6200, -1900, 'T69', 'VATB_LED0');
    AddPin(C, 6200, -2000, 'T66', 'VATB_LED1');
    AddPin(C, 6200, -2100, 'L22', 'VATB_RSSI0');
    AddPin(C, 6200, -2200, 'L20', 'VATB_RSSI1');
    AddPin(C, 6200, -2300, 'L29', 'VATB_TIA');
    AddPin(C, 6200, -2400, 'R27', 'VDD08D_SNS');
    AddPin(C, 6200, -2500, 'B21', 'VDD08PA_SNS');
    AddPin(C, 6200, -2600, 'B30', 'VDD08TIA_SNS');
    AddPin(C, 6200, -2700, 'T49', 'VDD50LED_SNS');
    AddPin(C, 6200, -2800, 'R21', 'VDDDRVLED_SNS');
    AddPin(C, 6200, -2900, 'R30', 'VDDLED_SNS');
    Commit(C);
End;

Procedure BuildBlock3;
Var C;
Begin
    AddTitle(8800, -700, 'RF-DIFFERENTIAL PAIR 100 OHM');
    C := NewBlock(8800, -1000, 1200, 700, 'RF_DIFFERENTIAL_PAIR_100_OHM');
    AddPin(C, 8800, -1100, 'B45', 'CLKEXTP<0>');
    AddPin(C, 8800, -1200, 'B39', 'CLKEXTM<0>');
    AddPin(C, 8800, -1300, 'L35', 'CLKEXTP<1>');
    AddPin(C, 8800, -1400, 'L37', 'CLKEXTM<1>');
    AddPin(C, 8800, -1500, 'B2', 'CLKOUTP_MUX');
    AddPin(C, 8800, -1600, 'B4', 'CLKOUTN_MUX');
    Commit(C);
End;

Procedure BuildBlock4;
Var C;
Begin
    AddTitle(11400, -700, 'RF-SINGLE ENDED 50 OHM');
    C := NewBlock(11400, -1000, 1200, 500, 'RF_SINGLE_ENDED_50_OHM');
    AddPin(C, 11400, -1100, 'L16', 'TEST_DLL_DESKEW_CKOUT');
    AddPin(C, 11400, -1200, 'R35', 'TEST_LED_STRB0_CKOUT');
    AddPin(C, 11400, -1300, 'L15', 'TEST_PLL4_CKOUT');
    AddPin(C, 11400, -1400, 'R37', 'TEST_TX_CKOUT');
    Commit(C);
End;

Procedure GenerateSchematic;
Begin
    If SchServer = Nil Then
    Begin
        ShowMessage('SchServer is nil -- the schematic editor is not loaded.');
        Exit;
    End;
    Doc := SchServer.GetCurrentSchDocument;
    If Doc = Nil Then
    Begin
        ShowMessage('No schematic is open. Create a blank one first: ' +
            'File > New > Schematic, make that tab active, then run again.');
        Exit;
    End;
    SchServer.ProcessControl.PreProcess(Doc, '');
    BuildBlock0;
    BuildBlock1;
    BuildBlock2;
    BuildBlock3;
    BuildBlock4;
    SchServer.ProcessControl.PostProcess(Doc, '');
    Doc.GraphicallyInvalidate;
    ShowMessage('Net-class schematic built on the active sheet. ' +
        'Use File > Save As to save it as a .SchDoc.');
End;