// Auto-generated by auto_probe_pcb.py -- Altium Sch-library DelphiScript.
// Removes every 'ProbeCard' component from the active schematic library.
// Open the .SchLib, make that tab the ACTIVE document, then
// File > Run Script... and run RemoveProbeCardComponents.
// Save the .SchLib afterwards to make the deletion stick.

Procedure RemoveProbeCardComponents;
Var
    Lib   : ISch_Lib;
    It    : ISch_Iterator;
    Cmp   : ISch_Component;
    Nxt   : ISch_Component;
    Count : Integer;
Begin
    If SchServer = Nil Then
    Begin
        ShowMessage('SchServer is nil -- the schematic editor is not loaded.');
        Exit;
    End;
    Lib := SchServer.GetCurrentSchDocument;
    If Lib = Nil Then
    Begin
        ShowMessage('No document open. Open the .SchLib and make it active.');
        Exit;
    End;
    If Lib.ObjectID <> eSchLib Then
    Begin
        ShowMessage('The active document is not a schematic library. ' +
            'Open the .SchLib tab and run this again.');
        Exit;
    End;

    Count := 0;
    It := Lib.SchLibIterator_Create;
    If It = Nil Then
    Begin
        ShowMessage('Could not create a library iterator.');
        Exit;
    End;
    Try
        It.AddFilter_ObjectSet(MkSet(eSchComponent));
        Cmp := It.FirstSchObject;
        While Cmp <> Nil Do
        Begin
            // step forward BEFORE removing -- deleting the object the
            // iterator sits on would invalidate its position.
            Nxt := It.NextSchObject;
            If Cmp.LibReference = 'ProbeCard' Then
            Begin
                Lib.RemoveSchComponent(Cmp);
                Count := Count + 1;
            End;
            Cmp := Nxt;
        End;
    Finally
        Lib.SchIterator_Destroy(It);
    End;

    Lib.GraphicallyInvalidate;
    If Count = 0 Then
        ShowMessage('No ProbeCard components found -- library is already clean.')
    Else
        ShowMessage('Removed ' + IntToStr(Count) + ' ProbeCard component(s). Save the .SchLib to keep the change.');
End;